config/routes.rb
Youtubueidcheck::Application.routes.draw do
  resources :youtube_ids, :only => [:index, :new, :create, :destroy] 

  root :to => 'youtube_ids#index'
end

app/models/youtube_id.rb
class YoutubeId < ActiveRecord::Base
  attr_accessible :y_id, :name
  
  validates :y_id, :presence => true, :uniqueness => true
  
  def extract_youtube_id_from_url()
    # check if url has 'youtube' string
    if self.y_id.strip == ""
      self.errors.add(:y_id, "not a valid url")
      return nil
    end
    
    # check if url has 'youtube' string
    if !self.y_id.include?("youtube.com")
      self.errors.add(:y_id, "not a youtube url")
      return nil
    end
    
    # parse uri
    begin
      tmp_params = URI.parse(self.y_id).query
    rescue URI::InvalidURIError => ex
      self.errors.add(:y_id, "not a valid url")
      return nil
    end
    
    # get query params
    if tmp_params.nil?
      self.errors.add(:y_id, "has no params")
      return nil
    end
    
    # parse query params and get youtube_id
    y_id = CGI.parse(tmp_params)['v']
    if y_id.length == 0
      self.errors.add(:y_id, "hasnot youtube id param")
      return nil
    end
    
    # get video info using Youtube API
    return y_id[0].strip
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/youtube_ids_controller.rb
require 'open-uri'

class YoutubeIdsController < ApplicationController
  # GET /youtube_ids
  # GET /youtube_ids.json
  def index
    @youtube_ids = YoutubeId.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @youtube_ids }
    end
  end

  # GET /youtube_ids/1
  # GET /youtube_ids/1.json
  def show
    @youtube_id = YoutubeId.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @youtube_id }
    end
  end

  # GET /youtube_ids/new
  # GET /youtube_ids/new.json
  def new
    @youtube_id = YoutubeId.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @youtube_id }
    end
  end

  # GET /youtube_ids/1/edit
  #def edit
  #  @youtube_id = YoutubeId.find(params[:id])
  #end

  # POST /youtube_ids
  # POST /youtube_ids.json
  def create
    @youtube_id = YoutubeId.new(params[:youtube_id])
    
    y_id = @youtube_id.extract_youtube_id_from_url()
    if y_id.nil?
      return_new_page()
      return
    end
    
    g_url = "http://gdata.youtube.com/feeds/api/videos?q=#{y_id}"
    doc = Nokogiri::HTML(open(g_url))
    
    # for testing
    #docfile = File.open("/work/youtube_g_exist.html", "r")
    #contents = docfile.read
    #doc = Nokogiri::HTML(contents)

    title_obj = doc.search("entry/title").first
    
    if !title_obj.nil?
      title = title_obj.text()
      @youtube_id = YoutubeId.new({:y_id => y_id, :name => title})
      
      respond_to do |format|
        if @youtube_id.save
          format.html { redirect_to new_youtube_id_path, notice: 'Video found.' }
          format.json { render json: @youtube_id, status: :created, location: @youtube_id }
        else
          format.html { render action: "new" }
          format.json { render json: @youtube_id.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        return_new_page("Video not found.")
        return
      end
    end
  end

=begin
  # PUT /youtube_ids/1
  # PUT /youtube_ids/1.json
  def update
    @youtube_id = YoutubeId.find(params[:id])

    respond_to do |format|
      if @youtube_id.update_attributes(params[:youtube_id])
        format.html { redirect_to @youtube_id, notice: 'Youtube was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @youtube_id.errors, status: :unprocessable_entity }
      end
    end
  end
=end

  # DELETE /youtube_ids/1
  # DELETE /youtube_ids/1.json
  def destroy
    @youtube_id = YoutubeId.find(params[:id])
    @youtube_id.destroy

    respond_to do |format|
      format.html { redirect_to youtube_ids_url }
      format.json { head :no_content }
    end
  end
  
  private
  def return_new_page(notice = nil)
    respond_to do |format| 
      flash[:notice] = notice
      format.html { render "new"}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/youtube_ids_helper.rb
module YoutubeIdsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Youtubueidcheck</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/youtube_ids/_form.html.erb
<%= simple_form_for(@youtube_id, :html => {:class => 'form-horizontal' }) do |f| %>
  <% if @youtube_id.errors.any? %>
    <% @youtube_id.errors.full_messages.each do |msg| %>
      <p class="alert"><%= msg %></p>
    <% end %>
  <% end %>
  <% if(notice) %><p class="alert"><%= notice %></p><% end %>
  <div class="field">
    <%= f.input :y_id, :label=>'Youtube URL',:input_html => {:style=>"width:400px;", :placeholder => "Example: http://www.youtube.com/watch?v=g0OzSpzYe6I"}  %>
  </div>
  <div class="actions pull-right">
    <%= f.submit "Submit", :class => "btn btn-primary" %> &nbsp;
    <%= link_to 'Back', youtube_ids_path, :class => "btn" %>
  </div>
<% end %>

app/views/youtube_ids/index.html.erb
<br/>

<h3>Youtube IDs</h3>
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<% @youtube_ids.each do |youtube_id| %>
  <tr>
    <td><%= youtube_id.y_id %></td>
    <td><%= youtube_id.name %></td>
    <td><%= link_to "Delete", youtube_id, :data => { :confirm => 'Are you sure?' }, :method => :delete %></td>
  </tr>
  </tbody>
<% end %>
</table>

<%= link_to 'New Youtube', new_youtube_id_path, :class => "btn"  %>

<br />

app/views/youtube_ids/new.html.erb
<br/>
<div class="span8">
  <legend>Check Youtube ID</legend>

  <%= render 'form' %>
</div>